### ISSUE TITLE
Semantic & grammatical issues with preface

### ISSUE THREAD

**Issue by bound-variable** [learnbyexample/learn_gnuawk#6]
The [preface](https://learnbyexample.github.io/learn_gnuawk/preface.html) says,

> As an analogy, consider learning to drive a bike or a car.

But, we don't _drive_ bikes; we _ride_ them.

Later, under Feedback and Errata it says,

> I would highly appreciate if you'd let me know how you felt about this book, it would help to improve this book as well as my future attempts.

This is a comma spliced run-on sentence. The _comma_ should be a _period_.

**Comment by learnbyexample** [comment]
Thanks for letting me know, I'll fix them in the next version.

I think I have many more such comma spliced run-on sentences.

**Comment by learnbyexample** [comment]
Fixed in version 2.0
